sudo: required
services:
  - docker

before_install:
  - docker build -t sorsok/react-test -f ./client/Dockerfile.dev ./client


script:
  - docker run sorsok/react-test npm run test -- --coverage

after_success:
  - docker build -t sorsok/schedulit-client ./client
  - docker build -t sorsok/schedulit-server ./server
  - docker build -t sorsok/schedulit-nginx ./nginx
  - echo "$DOCKER_PWD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push sorsok/schedulit-client 
  - docker push sorsok/schedulit-server 
  - docker push sorsok/schedulit-nginx 

