version: "3"
services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - "3000:80"
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    env_file:
      ./dev.env
    volumes:
      - "./server:/app"
      - "/app/node_modules"
    restart: always
    depends_on:
      - db

  client:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    volumes:
      - "./client:/app"
      - "/app/node_modules"
    restart: always

  db:
    image: mongo
    restart: always
    env_file:
      ./dev.env

    